# frozen_string_literal: true

require_relative "rterm/version"
require_relative "rterm/terminal_options"
require_relative "rterm/theme"
require_relative "rterm/service_container"
require_relative "rterm/common/types"
require_relative "rterm/common/event_emitter"
require_relative "rterm/common/buffer/constants"
require_relative "rterm/common/buffer/cell_data"
require_relative "rterm/common/buffer/cell"
require_relative "rterm/common/buffer/buffer_line"
require_relative "rterm/common/buffer/circular_list"
require_relative "rterm/common/buffer/buffer"
require_relative "rterm/common/buffer/buffer_set"
require_relative "rterm/common/parser/parser_state"
require_relative "rterm/common/parser/params"
require_relative "rterm/common/parser/escape_sequence_parser"
require_relative "rterm/common/parser/parser"
require_relative "rterm/common/parser/osc_parser"
require_relative "rterm/common/parser/dcs_parser"
require_relative "rterm/common/unicode/unicode_handler"
require_relative "rterm/common/unicode/table_builder"
require_relative "rterm/common/unicode/unicode_v6"
require_relative "rterm/common/unicode/unicode_v11"
require_relative "rterm/common/unicode/unicode_v15"
require_relative "rterm/common/charset/charset_table"
require_relative "rterm/common/charset/charsets"
require_relative "rterm/common/color/color_palette"
require_relative "rterm/common/color/color_manager"
require_relative "rterm/common/input/key_encoder"
require_relative "rterm/common/input/text_decoder"
require_relative "rterm/common/input/write_buffer"
require_relative "rterm/common/input/input_handler"
require_relative "rterm/common/core_terminal"
require_relative "rterm/headless/services/headless_service_container"
require_relative "rterm/headless/headless_terminal"
require_relative "rterm/pty/pty"
require_relative "rterm/terminal"
require_relative "rterm/browser_bridge/protocol_handler"
require_relative "rterm/browser_bridge/session_manager"
require_relative "rterm/browser_bridge/websocket_server"
require_relative "rterm/addons/base"
require_relative "rterm/addons/search/search"
require_relative "rterm/addons/serialize/serialize"
require_relative "rterm/addons/fit/fit"
require_relative "rterm/addons/web_links/web_links"

module RTerm
  class Error < StandardError; end
end
